namespace RedisNaruto.Consts;

public static class StreamConst
{
    /// <summary>
    /// The "~" value used with the MAXLEN option.
    /// </summary>
    public const string ApproximateMaxLen = "~";

    /// <summary>
    ///XADD 自动生成id
    /// </summary>
    public const string AutoGeneratedId = "*";

    /// <summary>
    /// XGROUP命令中使用的“$”值。指示只从流中读取新消息
    /// </summary>
    public const string NewMessages = "$";

    /// <summary>
    /// XGROUP命令中使用的“0”值。表示从流中读取所有消息。
    /// </summary>
    public const string AllMessages = "0";

    /// <summary>
    /// The "-" value used in the XRANGE, XREAD, and XREADGROUP commands. Indicates the minimum message ID from the stream.
    /// </summary>
    public const string MinValue = "-";

    /// <summary>
    /// The "+" value used in the XRANGE, XREAD, and XREADGROUP commands. Indicates the maximum message ID from the stream.
    /// </summary>
    public const string MaxValue = "+";

    #region internal

    /// <summary>
    /// 消费者
    /// </summary>
    internal static readonly string Consumers = "CONSUMERS";

    internal static readonly string Count = "COUNT";

    internal static readonly string Create = "CREATE";

    internal static readonly string DeleteConsumer = "DELCONSUMER";
    internal static readonly string CreateConsumer = "CREATECONSUMER";
    internal static readonly string Destroy = "DESTROY";
    internal static readonly string Group = "GROUP";

    internal static readonly string Groups = "GROUPS";

    internal static readonly string Limit = "LIMIT";
    internal static readonly string MaxLen = "MAXLEN";
    internal static readonly string MinId = "MINID";
    internal static readonly string MkStream = "MKSTREAM";

    internal static readonly string NOMKSTREAM = "NOMKSTREAM";
    internal static readonly string NoAck = "NOACK";

    internal static readonly string Stream = "STREAM";

    internal static readonly string Streams = "STREAMS";

    /// <summary>
    /// 空闲时间
    /// </summary>
    internal static readonly string Idle = "IDLE";

    internal static readonly string Time = "TIME";

    /// <summary>
    /// 重置 消息的传递次数
    /// </summary>
    internal static readonly string RetryCount = "RETRYCOUNT";

    internal static readonly string Block = "BLOCK";

    internal static readonly string Force = "FORCE";

    /// <summary>
    /// XCLAIM 仅返回id
    /// </summary>
    internal static readonly string JustId = "JUSTID";


    /// <summary>
    /// 设置消费组中流的id
    /// </summary>
    internal static readonly string SetId = "SETID";

    /// <summary>
    /// 目标db
    /// </summary>
    internal static readonly string Db = "DB";

    /// <summary>
    ///  是否替换
    /// </summary>
    internal static readonly string Replace = "REPLACE";

    #endregion
}